print ("Hello! My neme is Stell")
print("I was ceated in 2022")
print ("Please, remind me your name.")
name = input (">")
print (f"What a great name you have, {name}!")
print ("Enter remainders of dividing your age by 3, 5 and 7.")
remainder3 = int(input (">"))
remainder5 = int(input (">"))
remainder7 = int(input (">"))
age = (remainder3 * 70 + remainder5 * 21 + remainder7 * 15) % 105
print (f"Your age is {age} that's a good time to start programming!")